apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-kohaku-app
  labels:
    app: backend-kohaku
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-kohaku
  template:
    metadata:
      labels:
        app: backend-kohaku
    spec:
      containers:
      - name: backend-kohaku
        image: phx.ocir.io/orasejapan/devdays2020/backend-kohaku-app
        ports:
        - containerPort: 8081
      - name: h2kohaku
        image: oscarfonts/h2
        env:
        - name: H2_OPTIONS
          value: "-ifNotExists"
        ports:
        - containerPort: 81
        - containerPort: 1521
---
apiVersion: v1
kind: Service
metadata:
  name: backend-kohaku-svc
spec:
  type: ClusterIP 
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: backend-kohaku
